stages:
  - validate
  - compile
  - test
  - package
  - verify

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  APP_NAME: "helloword-cicd by David"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
    - target

# Download and use latest maven and jdk 17 Docker image
image: maven:3.9.5-amazoncorretto-17

compile_job:
  stage: compile
    - echo "Maven compile started"
    - mvn $MAVEN_CLI_OPTS clean compile

validate_job:
  stage: validate
    - echo "Maven validation started"
    - mvn $MAVEN_CLI_OPTS validate

test_job:
  stage: test
  script:
    - echo "This job1 unit tests"
    - mvn $MAVEN_CLI_OPTS test

package_job:
  stage: package
  script:
    - echo "Maven package started"
    - mvn $MAVEN_CLI_OPTS package

verify_job:
  stage: verify
  script:
    - echo "Maven verify started"
    - mvn $MAVEN_CLI_OPTS verify