stages:
  - test
  - build

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  APP_NAME: "helloword-cicd by David"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
    - target

# Download and use latest maven and jdk 17 Docker image
image: maven:3.9.5-amazoncorretto-17

test_job:
  stage: test
  script:
    - echo "Maven test started"
    - mvn $MAVEN_CLI_OPTS test

build_job:
  stage: build
  script:
    - echo "Maven build started"
    - mvn $MAVEN_CLI_OPTS package