stages:
  - build
  - test

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  APP_NAME: "helloword-cicd by David"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
    - target

# Download and use latest maven and jdk 17 Docker image
image: maven:3.9.5-amazoncorretto-17

build_job:
  stage: build
  script:
    - echo "Maven clean package started"
    - mvn clean package

test_job-unit-test:
  stage: test
  script:
    - echo "This job1 unit tests"
    - mvn test