image: maven:3.9.5-amazoncorretto-17

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  APP_NAME: "helloword-cicd by David"

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository
    - target

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests

Unit Test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test